services:
  app:
    build: .
    container_name: okimi-chan
    env_file: .env
    restart: always
    environment:
      - NODE_ENV=production
      - CACHE_CHAT_ID=-5069219296
    volumes:
      - ./logs:/app/logs